<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>$(AssemblyVersion)</Version>
        <Title>Lkhsoft.Collections</Title>
        <Authors>Maxime Loukhal</Authors>
        <Description>A set of useful collections such as graphs, binary search trees (AVL, Red Black), B-Tree, Trie and others</Description>
        <PackageProjectUrl>https://github.com/nakira974/Lkhsoft.Collections</PackageProjectUrl>
        <RepositoryUrl>https://github.com/nakira974/Lkhsoft.Collections</RepositoryUrl>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <Copyright>Copyright (c) Lkhsoft.Collections/Lkhsoft 2025</Copyright>
        <PackageLicenseUrl>https://github.com/nakira974/Lkhsoft.Collections/blob/trunk/LICENCE.md</PackageLicenseUrl>
        <PackageIcon>logo.png</PackageIcon>
        <PackageTags>Graphs BST B-Tree Trie</PackageTags>
        <LangVersion>default</LangVersion>
        <Company>Lkhsoft</Company>
        <AssemblyVersion>1.0.1</AssemblyVersion>
        <FileVersion>$(AssemblyVersion)</FileVersion>
        <RepositoryType>git</RepositoryType>
        <PackageReleaseNotes>XML and JSON serialization now supported</PackageReleaseNotes>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <Version>$(AssemblyVersion)-alpha</Version>
    </PropertyGroup>
    <ItemGroup>
      <None Update="logo.png">
        <Pack>True</Pack>
        <PackagePath></PackagePath>
      </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All"/>
    </ItemGroup>

</Project>
